version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=new_user
      - RABBITMQ_DEFAULT_PASS=new_password
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    driver: bridge
